### ISSUE TITLE
Addresses for RSK display incorrect checksum

### ISSUE THREAD

**Issue by jessgusclark** [rsksmart/rwallet#104] opened 2020-04-29 13:52 UTC
RSK addresses display an incorrect checksum. This throws an error in Nifty wallet when trying to transfer rbtc or rif.

**ios app**
![image](https://user-images.githubusercontent.com/766679/80603869-a38e4380-8a39-11ea-9cfe-dffa8929c349.png)

**nifty**

![image](https://user-images.githubusercontent.com/766679/80603947-bc96f480-8a39-11ea-84f9-9809c98670e7.png)

## mainnet

wallet address created: `0x9596797e8e36e30662aA2097eb826833164f9cf9`
expected address: `0x9596797E8E36E30662AA2097EB826833164f9Cf9`

## testnet

wallet address created: `0x044F4bF77E635018d6fC299883ca3A49e8406966`
expected checksum: `0x044F4Bf77E635018d6FC299883cA3A49E8406966`

- It can be verified here: https://address-validator.rsk.co/

A possible fix would be to use the [rskj-utils](https://github.com/rsksmart/rskjs-util) library's toChecksumAddress operation when displaying the address back to the user. 

--

I saw ticket #59 but it was marked as 'documentation' so I wasn't sure if this is a duplicate. If so, please ignore.

**Comment by chrisli30** [comment] 2020-04-29 22:20
@jessgusclark Hi Jesse, thanks for reporting this. According to EIP, when generate an address the app is supposed to pass in a parameter NetworkId.

Nifty wallet didn't do it, neither does MetaMask. However, we decided to apply that EIP the same as MyCrypto. That's the reason you see different checksum format. 

We have planned to address this issue. 
👍

**Comment by chrisli30** [comment] 2020-05-12 04:45
@imstar15 

We need to handle this error. We need to add a line of note below the address field showing "Got an error "Recipient address checksum is invalid?"" when user clicks on that we pop up a dialog, explain why and allow user to copy the address for MetaMask

**Comment by imstar15** [comment] 2020-05-21 08:35
1. MetaMask与rWallet生成钱包地址不一致，是因为使用的coin_type不一致.
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1581.md
m / purpose' / coin_type' / subpurpose' / key_type' / key_index
coin_type:
MetaMask: 60
rWallet: 137

2. 为了兼容MetaMask，我们导入助记词时需要生成两条链的地址，并向后端查询coin_type=60是否有交易记录，以此决定使用MetaMask地址，或者使用默认rWallet地址。

3. 因为derive两条链和网络交互时间较长，需要设计和实现一个合适的加载动画。

**Comment by imstar15** [comment] 2020-05-29 02:27
另外，ETH和RootStock地址checksum大小写也不一样的
`Rsk3.utils.toChecksumAddress(address, networkId);`
两者传入的networkId不一样

**Comment by chrisli30** [comment] 2020-09-16 20:09
Duplicate of #59

**Closed by chrisli30** 2020-09-16 20:09 UTC
Labels: duplicate
