### ISSUE TITLE
Android back button doesn't close the PIN window on exchange window

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#392] opened 2020-08-07 22:17 UTC
If I click on exchange button, and click Android back button on PIN window, doesn't close the PIN window.

![photo_2020-08-07_19-14-47](https://user-images.githubusercontent.com/1178856/89692612-94454e80-d8e2-11ea-9ba3-3f33e31ca79a.jpg)

**Comment by chrisli30** [comment] 2020-08-13 02:10
Duplicate of #356

**Closed** 2020-09-04 07:18 UTC
Labels: duplicate
