### ISSUE TITLE
dApp browser URL

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rwallet#384] opened 2020-08-06 15:28 UTC
The dapp browser is my favorite feature! Keep it up!! I see the url a little big, and i cannot tap it to re-browse another. I have to go back to the main screen, and this makes me loose my history - I cannot go back to the page I was using before.

![Image from iOS (4)](https://user-images.githubusercontent.com/36084092/89550586-2add1700-d7e0-11ea-956e-99af817edc3c.png)

**App & Device** (required)
 - Wallet App version: TestFlight latest
 - Device: [iPhone XR
 - OS version: iOS latest

**Comment by chrisli30** [comment] 2020-08-06 21:47
Thanks @ilanolkies . Yes, duplicate of #358

**Comment by AmazingBeerBelly** [comment] 2020-08-31 07:24
Fixed #1f7045a97a5fd3e2224f693d012f57d3d6bd16a0

**Closed by AmazingBeerBelly** 2020-08-31 07:24 UTC
Labels: duplicate
