### ISSUE TITLE
Add Bpro icon as Nifty extension added

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#480] opened 2020-09-16 13:59 UTC
Add Bpro icon as Nifty extension added

![Bpro](https://user-images.githubusercontent.com/1178856/93347613-a97b9a00-f80b-11ea-9182-1e285e5c66d5.jpg)

**Comment by chrisli30** [comment] 2020-10-01 19:56
Duplicate of #511

**Closed by chrisli30** 2020-10-01 19:56 UTC
Labels: duplicate, enhancement
