### ISSUE TITLE
Be able to swap bitcoin lightning to RBTC

### ISSUE THREAD

**Issue by bitcoinuser** [rsksmart/rwallet#209] opened 2020-06-07 14:49 UTC
Hi,

Today I saw this service: https://coinos.io/about that allows for example send bitcoin lightning and withdraw on Liquid or BItcoin.
I was thinking if they could add RBTC to the service, so I suggested here: (https://twitter.com/twiteis/status/1269639826606829569) 

If they integrate RBTC, Rwallet could support this on swap for example. Looks like the code is opensource: https://github.com/asoltys/coinos. Maybe even Rwallet could host on own server.

**Comment by bitcoinuser** [comment] 2020-06-07 14:52
I crated an issue on coinos: https://github.com/asoltys/coinos/issues/13

**Comment by chrisli30** [comment] 2020-10-01 19:50
duplicate of #365

**Closed by chrisli30** 2020-10-01 19:50 UTC
Labels: duplicate
