### ISSUE TITLE
BPRO no longer available on iOS

### ISSUE THREAD

**Issue by franamati** [rsksmart/rwallet#394] opened 2020-08-09 15:27 UTC
On latest iOS version (1.2.1), BPRO is no longer available to be selected on the asset list.

It would be great to have it back without needing to manually add it. Thanks!

Screenshot:
![BPRO on iOS](https://user-images.githubusercontent.com/8605599/89735831-966ef080-da3b-11ea-91e5-0c664b27d910.png)

**Comment by islatur** [comment] 2020-10-01 15:42
yes! i want this too! please!

**Comment by chrisli30** [comment] 2020-10-01 19:55
duplicate of #511

**Closed by chrisli30** 2020-10-01 19:55 UTC
Labels: duplicate, feature request
